openapi: 3.0.0
info:
  title: Order Service API
  description: API for managing book orders
  version: 1.0.0

servers:
  - url: http://localhost:3003

paths:
  /orders/get:
    get:
      summary: Get a list of all orders
      responses:
        '200':
          description: List of all orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

  /orders/create:
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: The order was created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '400':
          description: Invalid request
        '404':
          description: Order not found
        '500':
          description: Server error

components:
  schemas:
    Order:
      type: object
      required:
        - book_id
        - quantity
        - date
      properties:
        book_id:
          type: integer
        quantity:
          type: integer
        date:
          type: string
          format: date
